#!/bin/bash

source env/bin/activate
code_return=1
while [$code_return -eq 1]
do
    python3 app.py $1
    code_=$?
    if [$code_ -eq 0]
    then
        break
    else
        sudo service tor restart
        proxychains4 python3 app.py $1
        code_return=$?
    fi
done
