#!/bin/bash

car=$1
source /home/jagernau/avito/env/bin/activate
python3 /home/jagernau/avito/app.py $car
cod=$?

if [ $cod -ne 0 ]
then
    while true
    do
        sudo service tor restart
        sleep 5
        proxychains4 python3 /home/jagernau/avito/app.py $car
        if [ $? -eq 0 ]
        then
            break
        fi
    done
fi
